language: ruby

rvm:
- 2.3.1


script:
 - bash ./deploy.sh


branches:
  only:
  - master    

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
  - ENCRYPTION_LABEL: 47140654c715

 
sudo: false





















